"""Regression tests for scripts/summarize_run.py — the consolidated post-mortem.

review / user request 2026-05-19: a single tool that pulls audit.jsonl,
state.json, delegation_ledger.jsonl, session_pointer, and report.json
into ONE markdown/JSON summary so the operator does not have to grep
across multiple files to understand a run.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))
sys.path.insert(0, str(ROOT))


@pytest.fixture()
def fake_run(tmp_path: Path):
    """Build a realistic state.json + audit.jsonl + delegation_ledger.jsonl
    + session_pointer fixture and return its paths."""
    analysis = tmp_path / "analysis"
    analysis.mkdir()
    reports = tmp_path / "reports" / "TEST-CASE"
    reports.mkdir(parents=True)

    state = {
        "case_id": "TEST-CASE",
        "started_at": "2026-05-19T17:00:00.000Z",
        "updated_at": "2026-05-19T18:00:00.000Z",
        "findings": [
            # CONFIRMED with proper alt-hypothesis
            {
                "finding_id": "F-001", "finding_status": "CONFIRMED",
                "finding_type": "service_install", "confidence": 0.95,
                "execution_id": "E-005", "disposition": "ruled_out",
                "alternative_hypothesis": "legit IT deployment",
                "evidence_against_it": ["off-hours timestamp"],
                "confidence_support_inputs": {
                    "execution_id_source": "operator_supplied",
                },
            },
            # Demoted CONFIRMED candidate
            {
                "finding_id": "F-002", "finding_status": "ACTIVE",
                "finding_type": "process_injection", "confidence": 0.7,
                "execution_id": "E-099",
                "requires_re_extraction": True,
                "confidence_support_inputs": {
                    "execution_id_source": "state_autogenerated",
                    "confirmed_gate_blocks": [
                        "provenance:execution_id_autogenerated_no_audit_link",
                        "alternative_hypothesis:disposition_empty",
                    ],
                },
            },
            # Plain ACTIVE
            {
                "finding_id": "F-003", "finding_status": "ACTIVE",
                "finding_type": "sigma_hit", "confidence": 0.5,
                "execution_id": "E-007",
            },
        ],
        "analysis_lanes": [
            {
                "lane_id": "memory", "status": "COMPLETE",
                "assigned_agent": "memory-analyst",  # Path A
                "finding_ids": ["F-100"], "data_gaps": [],
            },
            {
                "lane_id": "disk_execution_persistence", "status": "COMPLETE_WITH_GAPS",
                "assigned_agent": "main-agent",  # Path B
                "finding_ids": ["F-001", "F-002"],
                "data_gaps": [
                    {"gap": "Amcache capped 2021-09-14", "severity": "HIGH"},
                ],
            },
        ],
        "executions": [
            {"execution_id": "E-001", "tool_name": "memory.list_processes"},
            {"execution_id": "E-002", "tool_name": "memory.scan_processes"},
        ],
    }
    (analysis / "state.json").write_text(json.dumps(state), encoding="utf-8")

    # audit.jsonl
    audit_rows = [
        {"timestamp": "2026-05-19T17:00:00.000Z", "execution_id": "E-001",
         "event_type": "completed", "tool": "memory.list_processes",
         "duration_seconds": 8.0, "exit_code": 0, "finding_ids_generated": ["F-100"]},
        {"timestamp": "2026-05-19T17:00:15.000Z", "execution_id": "E-002",
         "event_type": "completed", "tool": "memory.scan_processes",
         "duration_seconds": 14.0, "exit_code": 0, "finding_ids_generated": []},
        {"timestamp": "2026-05-19T17:01:00.000Z", "execution_id": "E-003",
         "event_type": "completed", "tool": "memory.detect_injection",
         "duration_seconds": 79.0, "exit_code": 0, "finding_ids_generated": []},
        {"timestamp": "2026-05-19T17:02:30.000Z", "execution_id": "E-004",
         "event_type": "completed", "tool": "disk.extract_mft_timeline",
         "duration_seconds": 132.0, "exit_code": 0, "finding_ids_generated": []},
        {"timestamp": "2026-05-19T17:05:00.000Z", "execution_id": "E-005",
         "event_type": "completed", "tool": "disk.summarize_evtx",
         "duration_seconds": 212.0, "exit_code": 0, "finding_ids_generated": ["F-001"]},
        # One failed tool call
        {"timestamp": "2026-05-19T17:06:00.000Z", "execution_id": "E-006",
         "event_type": "completed", "tool": "disk.extract_srum",
         "duration_seconds": 3.0, "exit_code": 1,
         "outputs_summary": "srum tool failed: file lock conflict"},
        # Sigma hunt
        {"timestamp": "2026-05-19T17:10:00.000Z", "execution_id": "E-007",
         "event_type": "completed", "tool": "detection.sigma_hunt",
         "duration_seconds": 442.0, "exit_code": 0,
         "finding_ids_generated": ["F-003"]},
        # Correlation
        {"timestamp": "2026-05-19T17:18:00.000Z", "execution_id": "E-068",
         "event_type": "completed", "tool": "correlation.compare_disk_and_memory",
         "duration_seconds": 3.0, "exit_code": 0},
        # Report attempts: first denied, second forced via allow_partial
        {"timestamp": "2026-05-19T17:19:00.000Z", "execution_id": "E-069",
         "event_type": "completed", "tool": "reporting.generate_report",
         "parameters": {"case_id": "TEST-CASE", "allow_partial": False},
         "duration_seconds": 0.5, "exit_code": 1,
         "outputs_summary": "report gated: needs_delegate"},
        {"timestamp": "2026-05-19T17:19:30.000Z", "execution_id": "E-070",
         "event_type": "completed", "tool": "reporting.generate_report",
         "parameters": {"case_id": "TEST-CASE", "allow_partial": True},
         "duration_seconds": 0.8, "exit_code": 0,
         "outputs_summary": "report generated: reports/TEST-CASE/report.html"},
    ]
    (analysis / "audit.jsonl").write_text(
        "\n".join(json.dumps(r) for r in audit_rows) + "\n", encoding="utf-8"
    )

    # Delegation ledger (session-scoped)
    ledger_path = tmp_path / "ledger.jsonl"
    session_id = "test-session-001"
    ledger_rows = [
        # current session
        {"timestamp": "2026-05-19T17:00:30.000Z", "session_id": session_id,
         "event": "delegation_required", "lane_id": "memory",
         "specialist": "memory-analyst", "tool": "memory.list_dlls"},
        {"timestamp": "2026-05-19T17:00:45.000Z", "session_id": session_id,
         "event": "task_attempt", "lane_id": "memory",
         "specialist": "memory-analyst", "attempt_id": "att-1"},
        {"timestamp": "2026-05-19T17:01:30.000Z", "session_id": session_id,
         "event": "task_outcome", "lane_id": "memory",
         "specialist": "memory-analyst", "attempt_id": "att-1",
         "outcome": "success", "excerpt": "{...}"},
        {"timestamp": "2026-05-19T17:02:00.000Z", "session_id": session_id,
         "event": "task_attempt", "lane_id": "disk_execution_persistence",
         "specialist": "prefetch-analyst", "attempt_id": "att-2"},
        {"timestamp": "2026-05-19T17:04:00.000Z", "session_id": session_id,
         "event": "task_outcome", "lane_id": "disk_execution_persistence",
         "specialist": "prefetch-analyst", "attempt_id": "att-2",
         "outcome": "timeout"},
        {"timestamp": "2026-05-19T17:18:30.000Z", "session_id": session_id,
         "event": "path_b_would_allow", "lane_id": "disk_execution_persistence",
         "specialist": "prefetch-analyst",
         "decision_basis": "failed_task_outcome_recorded"},
        # different session — must be filtered out
        {"timestamp": "2026-05-18T10:00:00.000Z", "session_id": "OTHER-SESSION",
         "event": "task_outcome", "lane_id": "memory",
         "specialist": "memory-analyst", "outcome": "timeout"},
    ]
    ledger_path.write_text(
        "\n".join(json.dumps(r) for r in ledger_rows) + "\n", encoding="utf-8"
    )

    # Session pointer
    session_ptr = tmp_path / "session.json"
    session_ptr.write_text(json.dumps({
        "session_id": session_id,
        "started_at": "2026-05-19T17:00:00.000Z",
        "cwd": str(tmp_path),
    }), encoding="utf-8")

    # Report stub
    (reports / "report.json").write_text(json.dumps({"status": "partial"}), encoding="utf-8")
    (reports / "report.html").write_text("<html></html>", encoding="utf-8")

    return {
        "analysis_dir": analysis,
        "ledger_path": ledger_path,
        "session_ptr": session_ptr,
        "reports_dir": reports,
        "session_id": session_id,
    }


# ---------------------------------------------------------------------------
# Behavior tests
# ---------------------------------------------------------------------------

def test_build_summary_session_section(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    assert s["session"]["session_id"] == "test-session-001"
    assert s["session"]["audit_duration_seconds"] is not None
    assert s["session"]["audit_duration_seconds"] > 1000  # ~19 min in fixture


def test_phase_timeline_buckets_correctly(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    tl = s["phase_timeline"]
    assert "1_memory" in tl, "memory phase should bucket tools"
    assert "2_disk" in tl
    assert "3_detection" in tl
    assert "5_correlation" in tl
    assert "7_reporting" in tl
    memory_eids = {e["execution_id"] for e in tl["1_memory"]}
    assert {"E-001", "E-002", "E-003"}.issubset(memory_eids)
    sigma_call = [e for e in tl["3_detection"] if e["tool"] == "detection.sigma_hunt"]
    assert sigma_call and sigma_call[0]["duration_seconds"] == 442.0


def test_lanes_attribute_path_a_vs_path_b(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    lanes = {l["lane_id"]: l for l in s["lanes"]}
    assert lanes["memory"]["path"] == "A", "memory has assigned_agent=memory-analyst"
    assert lanes["disk_execution_persistence"]["path"] == "B", \
        "disk lane assigned main-agent"
    # Ledger evidence should be attached
    assert lanes["memory"]["ledger"]["task_attempts"] == 1
    assert lanes["memory"]["ledger"]["outcomes"] == {"success": 1}
    assert lanes["disk_execution_persistence"]["ledger"]["outcomes"] == {"timeout": 1}


def test_ledger_filters_cross_session_rows(fake_run):
    """The OTHER-SESSION row must NOT appear in the summary."""
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    by_event = s["ledger_summary"]["by_event"]
    # In current session we have 1 delegation_required + 2 task_attempt + 2 task_outcome + 1 path_b_would_allow = 6
    assert s["ledger_summary"]["row_count"] == 6, (
        f"cross-session contamination: got {s['ledger_summary']['row_count']} rows"
    )


def test_findings_split_confirmed_demoted_other(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    findings = s["findings"]
    assert findings["total"] == 3
    assert findings["by_status"]["CONFIRMED"] == 1
    assert findings["by_status"]["ACTIVE"] == 2
    confirmed_ids = {f["finding_id"] for f in findings["confirmed_findings"]}
    assert confirmed_ids == {"F-001"}
    demoted_ids = {f["finding_id"] for f in findings["demoted_findings"]}
    assert "F-002" in demoted_ids
    demoted = [f for f in findings["demoted_findings"] if f["finding_id"] == "F-002"][0]
    assert "provenance:execution_id_autogenerated_no_audit_link" in demoted["blocks"]
    assert "alternative_hypothesis:disposition_empty" in demoted["blocks"]


def test_gate_coverage_flags_missing_and_failed(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    cov = s["gate_coverage"]
    assert cov["list_processes"]["ran"] is True
    assert cov["sigma_hunt"]["ran"] is True
    # Tools NOT in our audit fixture (scan_network, list_dlls, prefetch, amcache,
    # shimcache, registry, usn) should be flagged missing
    missing = set(cov.get("__missing__", []))
    assert "scan_network" in missing
    assert "extract_prefetch" in missing
    # Failed tool (srum exit=1) IS counted as ran (we recorded its execution)
    assert cov["extract_srum"]["ran"] is True
    assert cov["extract_srum"]["exit_code"] == 1


def test_report_attempts_captures_allow_partial_sequence(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    attempts = s["report_attempts"]
    assert len(attempts) == 2
    assert attempts[0]["allow_partial"] is False
    assert attempts[0]["exit_code"] == 1
    assert attempts[1]["allow_partial"] is True
    assert attempts[1]["exit_code"] == 0


def test_failures_section_surfaces_nonzero_exit(fake_run):
    from summarize_run import build_summary
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    failures = s["failures"]
    tools_in_failures = {f["tool"] for f in failures}
    # srum and the first generate_report both had exit_code != 0
    assert "disk.extract_srum" in tools_in_failures
    assert "reporting.generate_report" in tools_in_failures


def test_markdown_render_contains_key_sections(fake_run):
    from summarize_run import build_summary, render_markdown
    s = build_summary(
        "TEST-CASE",
        analysis_dir=fake_run["analysis_dir"],
        ledger_path=fake_run["ledger_path"],
        session_ptr_path=fake_run["session_ptr"],
        reports_dir=fake_run["reports_dir"],
    )
    md = render_markdown(s)
    expected_headers = [
        "# SAVVYDFIR Run Summary",
        "## Session",
        "## Phase Timeline",
        "## Lanes",
        "## Delegation Ledger",
        "## Findings",
        "## Gate Coverage",
        "## Report-Generation Attempts",
    ]
    for h in expected_headers:
        assert h in md, f"markdown missing section header: {h!r}"
    # The CONFIRMED finding should appear
    assert "F-001" in md
    # The demoted finding's blocks should be surfaced
    assert "provenance:execution_id_autogenerated_no_audit_link" in md


def test_summary_handles_empty_inputs(tmp_path: Path):
    """No state.json / audit.jsonl / ledger → summary still renders without crashing."""
    from summarize_run import build_summary, render_markdown
    empty_dir = tmp_path / "empty_analysis"
    empty_dir.mkdir()
    s = build_summary(
        "EMPTY",
        analysis_dir=empty_dir,
        ledger_path=tmp_path / "missing_ledger.jsonl",
        session_ptr_path=tmp_path / "missing_session.json",
        reports_dir=tmp_path / "missing_reports",
    )
    assert s["case_id"] == "EMPTY"
    assert s["findings"]["total"] == 0
    md = render_markdown(s)
    # All 15 mandatory tools should be flagged missing
    assert "MISSING (15)" in md


def test_mcp_tool_signature_present():
    """Source-text guard: the MCP tool wrapper must exist in server.py."""
    src = (ROOT / "sift_mcp" / "server.py").read_text()
    assert "def summarize_run(" in src
    assert "@mcp.tool()" in src
    # The tool must respect SAVVYDFIR_ANALYSIS_DIR override
    assert "SAVVYDFIR_ANALYSIS_DIR" in src
