"""Regression tests for the add_finding execution_id auto-link + alt-hypothesis schema.

peer reviewer consensus 2026-05-19 follow-up: Run-11 produced 0 CONFIRMED findings
because the framework's add_finding auto-generated orphan execution_ids
(no audit link) AND the alt-hypothesis fields were not reachable from
the MCP add_finding tool surface (only via the corroboration-analyst
subagent, which was unavailable that run).

These tests prove the fix:
  1. add_finding auto-links missing execution_id to the most recent
     execution row (preferring same tool_name), eliminating the
     "execution_id_autogenerated_no_audit_link" gate block.
  2. The add_finding MCP tool exposes the 5 alt-hypothesis fields +
     explicit execution_id parameter so main-agent (Path B) can
     populate them inline.
  3. A CONFIRMED finding created via add_finding with full alt-hypothesis
     fields survives both gates and stays CONFIRMED.
"""
from __future__ import annotations

import sys
import inspect
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------------
# Source-text guards (do not require fastmcp / a running server)
# ---------------------------------------------------------------------------

def test_state_add_finding_links_to_latest_execution_source_check():
    """Source-text guard: state.add_finding must search self._state['executions']
    for the most recent matching execution before falling back to
    generate_execution_id (the autogen path that produced orphan IDs)."""
    src = (ROOT / "sift_mcp" / "state.py").read_text()
    func_idx = src.find("def add_finding(self, finding")
    assert func_idx > 0
    end = src.find("\n    def ", func_idx + 1)
    body = src[func_idx:end if end > 0 else func_idx + 6000]

    assert "auto_linked_same_tool_execution" in body, (
        "add_finding must mark linked execution_ids with the "
        "'auto_linked_same_tool_execution' source so audit consumers "
        "can distinguish them from operator-supplied IDs."
    )
    assert "auto_linked_latest_tool_execution" in body, (
        "add_finding must fall back to the latest execution overall "
        "when no same-tool execution exists, marked as "
        "'auto_linked_latest_tool_execution'."
    )
    # autogen path must still exist as the final fallback (empty executions list)
    autogen_idx = body.find("state_autogenerated")
    same_tool_idx = body.find("auto_linked_same_tool_execution")
    assert 0 < same_tool_idx < autogen_idx, (
        "The link-to-real-execution path must run BEFORE the autogen "
        "fallback, otherwise we keep producing orphan IDs."
    )


def test_add_finding_mcp_tool_exposes_alt_hypothesis_params():
    """Source-text guard: the add_finding MCP tool must declare the 6 new
    parameters as part of its signature (so the agent can populate them
    via the tool call surface without the corroboration-analyst subagent)."""
    src = (ROOT / "sift_mcp" / "server.py").read_text()
    sig_idx = src.find("def add_finding(\n    case_id: str,")
    assert sig_idx > 0
    sig_end = src.find(") -> dict[str, Any]:", sig_idx)
    sig_block = src[sig_idx:sig_end]
    required_params = (
        "execution_id: str",
        "alternative_hypothesis: str",
        "evidence_that_would_support_it",
        "evidence_against_it",
        "disposition: str",
        "alternative_hypothesis_not_applicable_reason: str",
    )
    for param in required_params:
        assert param in sig_block, (
            f"add_finding MCP signature is missing required parameter: {param}. "
            f"Without it, Path B (main-agent inline) cannot populate the "
            f"alt-hypothesis fields and every CONFIRMED finding will be "
            f"demoted by the A2 gate."
        )


# ---------------------------------------------------------------------------
# Behavior tests via CaseStateManager (no fastmcp needed)
# ---------------------------------------------------------------------------

def _make_state(tmp_path: Path):
    """Build a real CaseStateManager bound to a temp state.json."""
    from sift_mcp.state import CaseStateManager
    sm = CaseStateManager(state_path=str(tmp_path / "state.json"))
    sm.load("TEST-CASE")
    return sm


def _record_execution(sm, execution_id: str, tool_name: str):
    """Inject a real execution row into state — mimics what _audit_logger.linked does."""
    with sm._lock:  # type: ignore[attr-defined]
        executions = sm._state.setdefault("executions", [])  # type: ignore[attr-defined]
        executions.append({
            "execution_id": execution_id,
            "tool_name": tool_name,
            "event_type": "completed",
            "iteration": 1,
        })


def test_add_finding_binds_orphan_eid_to_most_recent_same_tool(tmp_path):
    """When the agent calls add_finding without execution_id, the framework
    must bind to the most recent execution with the SAME tool_name (not
    autogenerate an orphan)."""
    sm = _make_state(tmp_path)
    _record_execution(sm, "E-001", "memory.list_processes")
    _record_execution(sm, "E-002", "disk.extract_mft_timeline")
    _record_execution(sm, "E-003", "memory.scan_network")
    _record_execution(sm, "E-004", "disk.extract_mft_timeline")

    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "test",
        "tool_name": "disk.extract_mft_timeline",
        "artifact_path": "/test/mft.csv",
        "artifact_type": "filesystem",
        "evidence_kind": "DISK_ARTIFACT",
        "description": "Suspicious MFT entry test finding",
        "confidence": 0.7,
        "finding_status": "ACTIVE",
        "iteration": 1,
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    assert stored is not None
    assert stored["execution_id"] == "E-004", (
        "Must bind to the most RECENT same-tool execution (E-004 over E-002)."
    )
    src = (stored.get("confidence_support_inputs") or {}).get("execution_id_source")
    assert src == "auto_linked_same_tool_execution", (
        f"Expected source='auto_linked_same_tool_execution', got {src!r}"
    )


def test_add_finding_falls_back_to_latest_overall_when_no_same_tool(tmp_path):
    """If no execution matches the tool_name, fall back to the latest
    execution overall (still avoids orphan autogen)."""
    sm = _make_state(tmp_path)
    _record_execution(sm, "E-001", "memory.list_processes")
    _record_execution(sm, "E-002", "disk.extract_mft_timeline")
    _record_execution(sm, "E-003", "memory.scan_network")

    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "test",
        "tool_name": "correlation.compare_disk_and_memory",
        "artifact_path": "/test/correlation.json",
        "artifact_type": "correlation",
        "evidence_kind": "CORRELATION",
        "description": "Correlation-based finding (no direct tool execution)",
        "confidence": 0.8,
        "finding_status": "ACTIVE",
        "iteration": 1,
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    src = (stored.get("confidence_support_inputs") or {}).get("execution_id_source")
    assert stored["execution_id"] == "E-003", (
        "Must bind to the latest execution overall when no same-tool match exists."
    )
    assert src == "auto_linked_latest_tool_execution"


def test_add_finding_autogen_fallback_only_when_no_executions_exist(tmp_path):
    """If state has no executions at all, the autogen fallback path runs
    (preserving the prior behavior for fresh / empty-state cases)."""
    sm = _make_state(tmp_path)
    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "test",
        "tool_name": "state.add_finding",
        "artifact_path": "/test/x.csv",
        "artifact_type": "memory",
        "evidence_kind": "INFERENCE",
        "description": "Fresh-state finding with no execution context",
        "confidence": 0.5,
        "finding_status": "ACTIVE",
        "iteration": 1,
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    src = (stored.get("confidence_support_inputs") or {}).get("execution_id_source")
    assert src == "state_autogenerated", (
        f"With no executions on record, the autogen path should fire. Got source={src!r}"
    )


def test_explicit_execution_id_is_respected(tmp_path):
    """If the agent supplies an explicit execution_id, the framework must
    use it verbatim (no auto-link override)."""
    sm = _make_state(tmp_path)
    _record_execution(sm, "E-001", "memory.list_processes")
    _record_execution(sm, "E-042", "disk.extract_mft_timeline")

    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "test",
        "tool_name": "disk.extract_mft_timeline",
        "artifact_path": "/test/mft.csv",
        "artifact_type": "filesystem",
        "evidence_kind": "DISK_ARTIFACT",
        "description": "Explicit-eid finding",
        "confidence": 0.9,
        "execution_id": "E-042",
        "finding_status": "ACTIVE",
        "iteration": 1,
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    assert stored["execution_id"] == "E-042"
    # No autogen / auto-link source marker should be inserted
    src = (stored.get("confidence_support_inputs") or {}).get("execution_id_source")
    assert src in (None, "operator_supplied"), (
        f"Explicit execution_id should not get a state_autogenerated source. Got {src!r}"
    )


def test_confirmed_finding_with_linked_eid_and_alt_hypothesis_stays_confirmed(tmp_path):
    """The end-to-end fix: a CONFIRMED finding created with auto-linked
    execution_id + full alt-hypothesis fields must survive BOTH gates
    and stay CONFIRMED. This is what Run-11 needed but couldn't do."""
    sm = _make_state(tmp_path)
    _record_execution(sm, "E-001", "disk.summarize_evtx")

    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "service_install",
        "tool_name": "disk.summarize_evtx",
        "artifact_path": "/test/System.evtx",
        "artifact_type": "evtx_event",
        "evidence_kind": "DISK_ARTIFACT",
        "description": "System.evtx EID 7045 service install correlated with MFT/USN drop",
        "confidence": 0.95,
        "finding_status": "CONFIRMED",
        "iteration": 1,
        "alternative_hypothesis": "Legitimate IT-deployed remote forensics agent",
        "evidence_against_it": [
            "no change-management ticket present in /etc/ITSM/tickets",
            "binary dropped from C:/Users/Public/Downloads — not standard IT path",
            "service install occurred outside business hours (03:01 UTC)",
        ],
        "disposition": "ruled_out",
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    assert stored["finding_status"] == "CONFIRMED", (
        "CONFIRMED finding with valid linked execution_id + full alt-hypothesis "
        "must survive both gates. This is the failure mode Run-11 exhibited."
    )
    assert not stored.get("requires_re_extraction"), (
        "requires_re_extraction must NOT be set when both gates pass."
    )
    assert stored["execution_id"] == "E-001"


def test_confirmed_finding_with_partial_alt_hypothesis_still_demoted(tmp_path):
    """Regression: even with a real execution_id, a CONFIRMED finding that
    lacks the full alt-hypothesis (e.g. disposition='not_resolved') must
    still be demoted per peer reviewer sign-off."""
    sm = _make_state(tmp_path)
    _record_execution(sm, "E-001", "memory.scan_network")

    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "c2_beacon",
        "tool_name": "memory.scan_network",
        "artifact_path": "/test/netscan.csv",
        "artifact_type": "network_connection",
        "evidence_kind": "MEMORY_ARTIFACT",
        "description": "Suspicious outbound connection on port 443",
        "confidence": 0.9,
        "finding_status": "CONFIRMED",
        "iteration": 1,
        "alternative_hypothesis": "Legitimate user browser session",
        "evidence_against_it": ["non-browser process holds socket"],
        "disposition": "not_resolved",  # The peer reviewer-mandated downgrade case
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    assert stored["finding_status"] == "ACTIVE", (
        "disposition='not_resolved' must downgrade per peer reviewer sign-off."
    )


def test_validate_path_does_not_collide_with_state_autogen(tmp_path):
    """Ensure that when add_finding auto-links to a real execution and then
    re-validates, the gate sees the linked eid (not E-000) and the finding
    passes the resolvability check."""
    from sift_mcp.semantics import _execution_id_resolvable

    sm = _make_state(tmp_path)
    _record_execution(sm, "E-007", "memory.list_processes")
    finding = {
        "case_id": "TEST-CASE",
        "finding_type": "process",
        "tool_name": "memory.list_processes",
        "artifact_path": "/test/pslist.csv",
        "artifact_type": "process",
        "evidence_kind": "MEMORY_ARTIFACT",
        "description": "rogue process",
        "confidence": 0.8,
        "finding_status": "ACTIVE",
        "iteration": 1,
    }
    fid = sm.add_finding(finding)
    stored = sm.get_finding(fid)
    ok, reason = _execution_id_resolvable(stored, sm)
    assert ok, (
        f"Auto-linked execution_id must resolve through the gate. "
        f"Got reason={reason!r}"
    )
