import tempfile
import unittest
from pathlib import Path

from sift_mcp.state import CaseStateManager


class StateValidationPhase34Tests(unittest.TestCase):
    def test_add_finding_canonicalizes_legacy_aliases_and_generates_execution_id(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-1")

            finding_id = manager.add_finding(
                {
                    "finding_type": "threat_detection",
                    "artifact_type": "evtx",
                    "artifact_path": r"C:\Windows\System32\winevt\Logs\Security.evtx",
                    "tool_name": "disk.summarize_evtx",
                    "evidence_kind": "DISK_ARTIFACT",
                    "finding_status": "ACTIVE",
                    "confidence": 0.8,
                    "description": "Security event log shows suspicious process creation activity.",
                    "supporting_indicators": ["EID 4688"],
                }
            )

            finding = manager.get_finding(finding_id)
            assert finding is not None
            self.assertEqual(finding["case_id"], "CASE-PH34-1")
            self.assertEqual(finding["artifact_type"], "disk")
            self.assertEqual(finding["artifact_subtype"], "evtx")
            self.assertEqual(finding["evidence_kind"], "observation")
            self.assertEqual(finding["finding_status"], "ACTIVE")
            self.assertRegex(finding["execution_id"], r"^E-\d{3,}$")
            self.assertEqual(
                finding["confidence_support_inputs"]["execution_id_source"],
                "state_autogenerated",
            )

    def test_add_finding_canonicalizes_agent_artifact_aliases(self) -> None:
        cases = [
            ("file_system", "file_system"),
            ("evtx_event", "evtx_event"),
            ("mft_entry", "mft_entry"),
            ("prefetch_record", "prefetch_record"),
        ]
        for artifact_type, expected_subtype in cases:
            with self.subTest(artifact_type=artifact_type), tempfile.TemporaryDirectory() as tmp_dir:
                manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
                manager.load("CASE-ALIAS")

                finding_id = manager.add_finding(
                    {
                        "case_id": "CASE-ALIAS",
                        "finding_type": "other",
                        "artifact_type": artifact_type,
                        "artifact_path": r"C:\Windows\Temp\artifact.bin",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.7,
                        "description": "Alias normalization test.",
                    }
                )

                finding = manager.get_finding(finding_id)
                assert finding is not None
                self.assertEqual(finding["artifact_type"], "disk")
                self.assertEqual(finding["artifact_subtype"], expected_subtype)

    def test_unsupported_artifact_type_error_lists_valid_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-BAD-ALIAS")

            with self.assertRaisesRegex(
                Exception,
                "valid_artifact_types=.*supported_aliases=",
            ):
                manager.add_finding(
                    {
                        "case_id": "CASE-BAD-ALIAS",
                        "finding_type": "other",
                        "artifact_type": "not_a_real_artifact",
                        "artifact_path": r"C:\Windows\Temp\artifact.bin",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.7,
                        "description": "Bad artifact alias test.",
                    }
                )

    def test_add_finding_maps_legacy_hypothesis_status_to_evidence_kind(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-2")

            finding_id = manager.add_finding(
                {
                    "case_id": "CASE-PH34-2",
                    "finding_type": "persistence",
                    "artifact_type": "registry_key",
                    "artifact_path": r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run",
                    "tool_name": "state.add_finding",
                    "execution_id": "E-111",
                    "iteration": 1,
                    "evidence_kind": "DISK_ARTIFACT",
                    "finding_status": "HYPOTHESIS",
                    "confidence": 0.75,
                    "description": "Registry autorun entry points to an AppData executable path.",
                    "supporting_indicators": [r"C:\Users\Alice\AppData\Roaming\evil.exe"],
                }
            )

            finding = manager.get_finding(finding_id)
            assert finding is not None
            self.assertEqual(finding["artifact_type"], "disk")
            self.assertEqual(finding["artifact_subtype"], "registry_key")
            self.assertEqual(finding["evidence_kind"], "hypothesis")
            self.assertEqual(finding["finding_status"], "ACTIVE")

    def test_add_finding_rejects_invalid_mitre_and_missing_required_fields(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-3")

            with self.assertRaises(Exception):
                manager.add_finding(
                    {
                        "case_id": "CASE-PH34-3",
                        "finding_type": "other",
                        "artifact_type": "disk",
                        "artifact_path": r"C:\Temp\evil.exe",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.6,
                        "description": "Missing tool name should not be accepted into state.",
                    }
                )

            with self.assertRaises(Exception):
                manager.add_finding(
                    {
                        "case_id": "CASE-PH34-3",
                        "finding_type": "other",
                        "artifact_type": "disk",
                        "artifact_path": r"C:\Temp\evil.exe",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-002",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.6,
                        "description": "Invalid MITRE IDs should be rejected before persistence.",
                        "mitre_tactic": "TACTIC-1",
                    }
                )

    def test_update_finding_normalizes_link_fields_and_support_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-4")

            finding_id = manager.add_finding(
                {
                    "case_id": "CASE-PH34-4",
                    "finding_type": "other",
                    "artifact_type": "memory",
                    "artifact_path": r"mem://pid/1234",
                    "tool_name": "memory.scan_processes",
                    "execution_id": "E-020",
                    "iteration": 1,
                    "evidence_kind": "observation",
                    "finding_status": "ACTIVE",
                    "confidence": 0.7,
                    "description": "Process scan identified an anomalous process relationship.",
                    "supporting_indicators": ["pid:1234"],
                }
            )

            updated = manager.update_finding(
                finding_id,
                contradicted_by="correlation:manual_review",
                corroborated_by=("memory_process",),
            )

            self.assertEqual(updated["contradicted_by"], ["correlation:manual_review"])
            self.assertEqual(updated["corroborated_by"], ["memory_process"])
            self.assertEqual(updated["promotion_eligibility"], "blocked_by_contradiction")
            self.assertIn("memory", updated["supporting_tool_families"])
            self.assertIn("memory", updated["supporting_artifact_families"])


class ArtifactSubtypePathDeriveTests(unittest.TestCase):
    """Runtime source-of-truth derive: analyst findings (tool_name=
    state.submit_finding) with blank artifact_subtype recover it from the
    staged /artifacts/<subtype>/ segment of artifact_path. review sign-off
    2026-05-30 (review-runtime-subtype-derive-2026-05-30.md)."""

    def _add(self, manager, *, artifact_type="disk", artifact_subtype=None,
             artifact_path="", tool_name="state.submit_finding"):
        finding = {
            "case_id": "CASE-SUBTYPE",
            "finding_type": "exfiltration",
            "artifact_type": artifact_type,
            "artifact_path": artifact_path,
            "tool_name": tool_name,
            "execution_id": "E-001",
            "iteration": 1,
            "evidence_kind": "observation",
            "finding_status": "ACTIVE",
            "confidence": 0.7,
            "description": "Path-derive subtype regression fixture.",
        }
        if artifact_subtype is not None:
            finding["artifact_subtype"] = artifact_subtype
        fid = manager.add_finding(finding)
        return manager.get_finding(fid)

    def _mgr(self, tmp_dir):
        m = CaseStateManager(str(Path(tmp_dir) / "state.json"))
        m.load("CASE-SUBTYPE")
        return m

    def test_derives_subtype_from_standard_and_raw_paths(self) -> None:
        cases = [
            ("/cases/X/artifacts/mft/mft_timeline.csv", "mft"),
            ("/cases/X/artifacts/usn/usn_journal.csv", "usn"),
            ("/cases/X/artifacts/evtx/evtx_timeline.csv", "evtx"),
            ("/cases/X/artifacts/prefetch/prefetch.csv", "prefetch"),
            ("/cases/X/artifacts/raw/srum/SRUDB.dat", "srum"),       # raw/ intermediate
            ("/cases/X/artifacts/raw/evtx", "evtx"),                  # no trailing slash
            ("<case-dir>/artifacts/mft/x.csv", "mft"),                # redacted prefix
            (r"C:\cases\X\artifacts\registry\SOFTWARE", "registry"),  # windows separators
        ]
        for path, expected in cases:
            with self.subTest(path=path), tempfile.TemporaryDirectory() as tmp:
                f = self._add(self._mgr(tmp), artifact_path=path)
                self.assertEqual(f["artifact_subtype"], expected)

    def test_unrecognized_or_missing_path_stays_blank(self) -> None:
        # All non-empty (OBSERVATION findings require a path); none match the
        # /artifacts/<allowed-subtype>/ contract, so subtype stays blank.
        for path in (
            "/cases/X/artifacts/unknown_dir/x.csv",   # dir not in allowlist
            "<legacy-unavailable>",
            r"ROOT\ControlSet001\Services\bam\State",  # registry path, no /artifacts/
            "/cases/X/SYSTEM_AppCompatCache.csv",      # non-standard, no /artifacts/
        ):
            with self.subTest(path=path), tempfile.TemporaryDirectory() as tmp:
                f = self._add(self._mgr(tmp), artifact_path=path)
                self.assertIn(f.get("artifact_subtype"), (None, ""))

    def test_explicit_subtype_is_never_overridden(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                artifact_subtype="amcache",
                artifact_path="/cases/X/artifacts/mft/mft_timeline.csv",
            )
            self.assertEqual(f["artifact_subtype"], "amcache")  # explicit wins over path

    def test_tool_name_canonicalization_wins_over_path(self) -> None:
        # tool_name yields a subtype -> path derive must not run.
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                artifact_type="evtx",  # alias -> disk + subtype evtx via tool/type
                tool_name="disk.summarize_evtx",
                artifact_path="/cases/X/artifacts/prefetch/prefetch.csv",
            )
            self.assertEqual(f["artifact_subtype"], "evtx")  # NOT prefetch

    def test_derived_subtype_is_retrievable_via_get_findings(self) -> None:
        # Guards against the state.py exact-match split: a path-derived subtype
        # must be queryable through get_findings(artifact_type=<subtype>).
        with tempfile.TemporaryDirectory() as tmp:
            m = self._mgr(tmp)
            self._add(m, artifact_path="/cases/X/artifacts/mft/mft_timeline.csv")
            hits = m.get_findings(artifact_type="mft")
            self.assertEqual(len(hits), 1)
            self.assertEqual(hits[0]["artifact_subtype"], "mft")

    def test_derive_does_not_change_confidence_or_status(self) -> None:
        # Metadata-only: deriving subtype must not shift confidence,
        # fk_source_class, or finding_status (no fk-multiplier side effect).
        with tempfile.TemporaryDirectory() as tmp_a, tempfile.TemporaryDirectory() as tmp_b:
            with_path = self._add(
                self._mgr(tmp_a),
                artifact_path="/cases/X/artifacts/mft/mft_timeline.csv",
            )
            without_path = self._add(self._mgr(tmp_b), artifact_path="<legacy-unavailable>")
            self.assertEqual(with_path["confidence"], without_path["confidence"])
            self.assertEqual(
                with_path.get("fk_source_class"), without_path.get("fk_source_class")
            )
            self.assertEqual(with_path["finding_status"], without_path["finding_status"])

    def test_non_disk_findings_are_not_path_derived(self) -> None:
        # memory/correlation findings bucket by artifact_type; a disk-looking
        # path must not stamp a disk subtype onto them.
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                artifact_type="memory",
                tool_name="memory.scan_network",
                artifact_path="/cases/X/artifacts/mft/mft_timeline.csv",
            )
            self.assertIn(f.get("artifact_subtype"), (None, ""))

    # --- tool_name derive (auto-generated disk findings) -----------------

    def test_derives_subtype_from_tool_name_when_type_already_disk(self) -> None:
        # artifact_type="disk" is already canonical, so _canonicalize skips the
        # tool_name -> the new tool_name derive must recover it. Registry path
        # is a ROOT\... hive key with NO /artifacts/ segment (path derive can't).
        cases = [
            ("disk.extract_registry_run_keys", r"ROOT\ControlSet001\Services\bam", "registry"),
            ("disk.summarize_evtx", r"ROOT\System\foo", "evtx"),
            ("disk.extract_shimcache", r"C:\Windows\AppCompat\x", "shimcache"),
        ]
        for tool, path, expected in cases:
            with self.subTest(tool=tool), tempfile.TemporaryDirectory() as tmp:
                f = self._add(self._mgr(tmp), tool_name=tool, artifact_path=path)
                self.assertEqual(f["artifact_subtype"], expected)

    def test_tool_derive_wins_over_conflicting_path(self) -> None:
        # tool_name is authoritative; it runs before path parse.
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                tool_name="disk.extract_registry_run_keys",
                artifact_path="/cases/X/artifacts/mft/mft_timeline.csv",
            )
            self.assertEqual(f["artifact_subtype"], "registry")  # NOT mft

    def test_explicit_subtype_wins_over_tool_derive(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                artifact_subtype="amcache",
                tool_name="disk.extract_registry_run_keys",
                artifact_path=r"ROOT\ControlSet001\Services\bam",
            )
            self.assertEqual(f["artifact_subtype"], "amcache")

    def test_unknown_tool_with_unmatched_path_stays_blank(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            f = self._add(
                self._mgr(tmp),
                tool_name="state.submit_finding",
                artifact_path=r"ROOT\ControlSet001\Services\bam",  # no /artifacts/
            )
            self.assertIn(f.get("artifact_subtype"), (None, ""))


if __name__ == "__main__":
    unittest.main()
