import tempfile
import unittest
from pathlib import Path

from sift_mcp.state import CaseStateManager


class StateValidationPhase34Tests(unittest.TestCase):
    def test_add_finding_canonicalizes_legacy_aliases_and_generates_execution_id(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-1")

            finding_id = manager.add_finding(
                {
                    "finding_type": "threat_detection",
                    "artifact_type": "evtx",
                    "artifact_path": r"C:\Windows\System32\winevt\Logs\Security.evtx",
                    "tool_name": "disk.summarize_evtx",
                    "evidence_kind": "DISK_ARTIFACT",
                    "finding_status": "ACTIVE",
                    "confidence": 0.8,
                    "description": "Security event log shows suspicious process creation activity.",
                    "supporting_indicators": ["EID 4688"],
                }
            )

            finding = manager.get_finding(finding_id)
            assert finding is not None
            self.assertEqual(finding["case_id"], "CASE-PH34-1")
            self.assertEqual(finding["artifact_type"], "disk")
            self.assertEqual(finding["artifact_subtype"], "evtx")
            self.assertEqual(finding["evidence_kind"], "observation")
            self.assertEqual(finding["finding_status"], "ACTIVE")
            self.assertRegex(finding["execution_id"], r"^E-\d{3,}$")
            self.assertEqual(
                finding["confidence_support_inputs"]["execution_id_source"],
                "state_autogenerated",
            )

    def test_add_finding_canonicalizes_agent_artifact_aliases(self) -> None:
        cases = [
            ("file_system", "file_system"),
            ("evtx_event", "evtx_event"),
            ("mft_entry", "mft_entry"),
            ("prefetch_record", "prefetch_record"),
        ]
        for artifact_type, expected_subtype in cases:
            with self.subTest(artifact_type=artifact_type), tempfile.TemporaryDirectory() as tmp_dir:
                manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
                manager.load("CASE-ALIAS")

                finding_id = manager.add_finding(
                    {
                        "case_id": "CASE-ALIAS",
                        "finding_type": "other",
                        "artifact_type": artifact_type,
                        "artifact_path": r"C:\Windows\Temp\artifact.bin",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.7,
                        "description": "Alias normalization test.",
                    }
                )

                finding = manager.get_finding(finding_id)
                assert finding is not None
                self.assertEqual(finding["artifact_type"], "disk")
                self.assertEqual(finding["artifact_subtype"], expected_subtype)

    def test_unsupported_artifact_type_error_lists_valid_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-BAD-ALIAS")

            with self.assertRaisesRegex(
                Exception,
                "valid_artifact_types=.*supported_aliases=",
            ):
                manager.add_finding(
                    {
                        "case_id": "CASE-BAD-ALIAS",
                        "finding_type": "other",
                        "artifact_type": "not_a_real_artifact",
                        "artifact_path": r"C:\Windows\Temp\artifact.bin",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.7,
                        "description": "Bad artifact alias test.",
                    }
                )

    def test_add_finding_maps_legacy_hypothesis_status_to_evidence_kind(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-2")

            finding_id = manager.add_finding(
                {
                    "case_id": "CASE-PH34-2",
                    "finding_type": "persistence",
                    "artifact_type": "registry_key",
                    "artifact_path": r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run",
                    "tool_name": "state.add_finding",
                    "execution_id": "E-111",
                    "iteration": 1,
                    "evidence_kind": "DISK_ARTIFACT",
                    "finding_status": "HYPOTHESIS",
                    "confidence": 0.75,
                    "description": "Registry autorun entry points to an AppData executable path.",
                    "supporting_indicators": [r"C:\Users\Alice\AppData\Roaming\evil.exe"],
                }
            )

            finding = manager.get_finding(finding_id)
            assert finding is not None
            self.assertEqual(finding["artifact_type"], "disk")
            self.assertEqual(finding["artifact_subtype"], "registry_key")
            self.assertEqual(finding["evidence_kind"], "hypothesis")
            self.assertEqual(finding["finding_status"], "ACTIVE")

    def test_add_finding_rejects_invalid_mitre_and_missing_required_fields(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-3")

            with self.assertRaises(Exception):
                manager.add_finding(
                    {
                        "case_id": "CASE-PH34-3",
                        "finding_type": "other",
                        "artifact_type": "disk",
                        "artifact_path": r"C:\Temp\evil.exe",
                        "execution_id": "E-001",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.6,
                        "description": "Missing tool name should not be accepted into state.",
                    }
                )

            with self.assertRaises(Exception):
                manager.add_finding(
                    {
                        "case_id": "CASE-PH34-3",
                        "finding_type": "other",
                        "artifact_type": "disk",
                        "artifact_path": r"C:\Temp\evil.exe",
                        "tool_name": "state.add_finding",
                        "execution_id": "E-002",
                        "iteration": 1,
                        "evidence_kind": "observation",
                        "finding_status": "ACTIVE",
                        "confidence": 0.6,
                        "description": "Invalid MITRE IDs should be rejected before persistence.",
                        "mitre_tactic": "TACTIC-1",
                    }
                )

    def test_update_finding_normalizes_link_fields_and_support_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            manager = CaseStateManager(str(Path(tmp_dir) / "state.json"))
            manager.load("CASE-PH34-4")

            finding_id = manager.add_finding(
                {
                    "case_id": "CASE-PH34-4",
                    "finding_type": "other",
                    "artifact_type": "memory",
                    "artifact_path": r"mem://pid/1234",
                    "tool_name": "memory.scan_processes",
                    "execution_id": "E-020",
                    "iteration": 1,
                    "evidence_kind": "observation",
                    "finding_status": "ACTIVE",
                    "confidence": 0.7,
                    "description": "Process scan identified an anomalous process relationship.",
                    "supporting_indicators": ["pid:1234"],
                }
            )

            updated = manager.update_finding(
                finding_id,
                contradicted_by="correlation:manual_review",
                corroborated_by=("memory_process",),
            )

            self.assertEqual(updated["contradicted_by"], ["correlation:manual_review"])
            self.assertEqual(updated["corroborated_by"], ["memory_process"])
            self.assertEqual(updated["promotion_eligibility"], "blocked_by_contradiction")
            self.assertIn("memory", updated["supporting_tool_families"])
            self.assertIn("memory", updated["supporting_artifact_families"])


if __name__ == "__main__":
    unittest.main()
