"""Regression tests for Tier-A1 execution-ID provenance gate.

peer reviewer consensus 2026-05-19: CONFIRMED status requires a resolvable
execution_id (or operator override at report layer via allow_partial=True).
The finding-level gate is STRICT — `requires_re_extraction` is a state
marker, not a bypass.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------------
# Pure-function tests for _execution_id_resolvable (no fastmcp / state needed)
# ---------------------------------------------------------------------------

class _FakeStateManager:
    """Minimal stand-in supporting get_execution for the gate tests."""
    def __init__(self, executions: dict[str, dict[str, Any]] | None = None):
        self._execs = dict(executions or {})

    def get_execution(self, eid: str):
        return self._execs.get(eid)


def _import_helper():
    from sift_mcp.semantics import _execution_id_resolvable
    return _execution_id_resolvable


def test_resolvable_requires_real_execution_id():
    """Placeholder E-000 must fail the gate."""
    helper = _import_helper()
    sm = _FakeStateManager({"E-001": {"tool_name": "disk.x"}})
    ok, reason = helper({"execution_id": "E-000"}, sm)
    assert not ok
    assert "placeholder" in reason or "missing" in reason


def test_resolvable_rejects_autogenerated_execution_id():
    """state_autogenerated execution_id_source must fail the gate."""
    helper = _import_helper()
    sm = _FakeStateManager({"E-007": {"tool_name": "disk.x"}})
    ok, reason = helper({
        "execution_id": "E-007",
        "confidence_support_inputs": {"execution_id_source": "state_autogenerated"},
    }, sm)
    assert not ok
    assert "autogenerated" in reason


def test_resolvable_passes_when_audit_row_exists():
    """A real execution_id matching an audit row passes the gate."""
    helper = _import_helper()
    sm = _FakeStateManager({"E-042": {"tool_name": "disk.extract_mft_timeline"}})
    ok, reason = helper({"execution_id": "E-042"}, sm)
    assert ok
    assert reason == "ok"


def test_resolvable_fails_when_audit_row_missing():
    """Real-looking execution_id that doesn't resolve in the ledger fails."""
    helper = _import_helper()
    sm = _FakeStateManager({"E-001": {"tool_name": "disk.x"}})
    ok, reason = helper({"execution_id": "E-999"}, sm)
    assert not ok
    assert "unresolvable" in reason


def test_resolvable_no_state_manager_context_passes():
    """Migration / isolated test mode: no state_manager → accept (defense
    is at report layer)."""
    helper = _import_helper()
    ok, reason = helper({"execution_id": "E-001"}, None)
    assert ok
    assert "no_state_manager_context" in reason


def test_requires_re_extraction_is_not_a_bypass():
    """Critical: requires_re_extraction=True must NOT bypass the gate.
    The flag is a state marker; operator override happens at report level."""
    helper = _import_helper()
    sm = _FakeStateManager({"E-001": {"tool_name": "disk.x"}})
    ok, reason = helper({
        "execution_id": "E-000",
        "requires_re_extraction": True,
    }, sm)
    assert not ok, (
        "requires_re_extraction must NOT be a bypass at the finding-level "
        "gate. Operator override happens via allow_partial=True at report level."
    )


# ---------------------------------------------------------------------------
# Integration: validate_and_prepare_finding demotes CONFIRMED on gate fail
# ---------------------------------------------------------------------------

def test_validate_and_prepare_demotes_confirmed_on_provenance_failure():
    """A CONFIRMED finding with a non-resolvable execution_id must be
    demoted to ACTIVE and have requires_re_extraction set."""
    from sift_mcp.semantics import validate_and_prepare_finding
    sm = _FakeStateManager({})  # empty ledger — no execution resolves
    incoming = {
        "case_id": "TEST",
        "finding_type": "test_finding",
        "tool_name": "test.tool",
        "execution_id": "E-999",   # not in ledger
        "iteration": 1,
        "evidence_kind": "INFERENCE",
        "finding_status": "CONFIRMED",  # caller tried to promote
        "confidence": 0.95,
        "description": "Test finding for provenance gate regression.",
        "artifact_path": "/test/artifact.csv",
        "artifact_type": "memory",
    }
    out = validate_and_prepare_finding(incoming, state_manager=sm)
    assert out["finding_status"] == "ACTIVE", (
        f"Finding must be demoted from CONFIRMED to ACTIVE when execution_id "
        f"does not resolve. Got: {out['finding_status']}"
    )
    assert out.get("requires_re_extraction") is True, (
        "Demoted finding must carry requires_re_extraction=True as a state marker."
    )
    blocks = (out.get("confidence_support_inputs") or {}).get("confirmed_gate_blocks") or []
    assert any("provenance:" in b for b in blocks), (
        f"confirmed_gate_blocks must record the provenance reason. Got: {blocks}"
    )


def test_validate_and_prepare_keeps_confirmed_when_provenance_resolves():
    """Happy path: real execution_id, resolves, alt-hypothesis populated → CONFIRMED stays."""
    from sift_mcp.semantics import validate_and_prepare_finding
    sm = _FakeStateManager({"E-042": {"tool_name": "test.tool"}})
    incoming = {
        "case_id": "TEST",
        "finding_type": "test_finding",
        "tool_name": "test.tool",
        "execution_id": "E-042",
        "iteration": 1,
        "evidence_kind": "INFERENCE",
        "finding_status": "CONFIRMED",
        "confidence": 0.95,
        "description": "Test finding with full provenance and alt-hypothesis.",
        "artifact_path": "/test/artifact.csv",
        "artifact_type": "memory",
        "alternative_hypothesis": "Legitimate IT use",
        "evidence_against_it": ["timestomp", "no_change_ticket"],
        "disposition": "ruled_out",
    }
    out = validate_and_prepare_finding(incoming, state_manager=sm)
    assert out["finding_status"] == "CONFIRMED", (
        f"Finding with valid provenance + populated alt-hypothesis must stay "
        f"CONFIRMED. Got: {out['finding_status']}"
    )
    assert not out.get("requires_re_extraction")


def test_active_finding_passes_through_unchanged_even_with_bad_provenance():
    """The gate only affects CONFIRMED transitions. ACTIVE findings with
    placeholder execution_id pass through (auto-allocation happens later
    in state.py:add_finding)."""
    from sift_mcp.semantics import validate_and_prepare_finding
    sm = _FakeStateManager({})
    incoming = {
        "case_id": "TEST",
        "finding_type": "test_finding",
        "tool_name": "test.tool",
        "execution_id": "E-000",  # placeholder, OK for ACTIVE
        "iteration": 1,
        "evidence_kind": "INFERENCE",
        "finding_status": "ACTIVE",
        "confidence": 0.40,
        "description": "Low-confidence active finding with placeholder execution_id.",
        "artifact_path": "/test/artifact.csv",
        "artifact_type": "memory",
    }
    out = validate_and_prepare_finding(incoming, state_manager=sm)
    assert out["finding_status"] == "ACTIVE"
    # Gate only fires on CONFIRMED, so no requires_re_extraction
    assert not out.get("requires_re_extraction")


def test_source_text_helper_is_strict():
    """Source-text guard: _execution_id_resolvable must NOT use
    requires_re_extraction as a bypass. The function should reject the
    pattern that returns True on requires_re_extraction."""
    import inspect
    from sift_mcp.semantics import _execution_id_resolvable
    src = inspect.getsource(_execution_id_resolvable)
    # The bypass pattern must be GONE
    assert 'finding.get("requires_re_extraction")' not in src, (
        "peer reviewer consensus regression: _execution_id_resolvable must not "
        "treat requires_re_extraction as a finding-level bypass. Operator "
        "override happens at report layer via allow_partial=True."
    )
    # Must check execution_id_source = state_autogenerated
    assert "state_autogenerated" in src, (
        "Helper must reject autogenerated execution_ids that lack audit links."
    )
